modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/dracomelette/issues"
[[mods]]
modId="dracomelette"
version="${file.jarVersion}"
displayName="Dracomelette"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dracomelette"
logoFile="icon.png"
authors="MoriyaShiine, cybercat5555"
description='''Cookable dragon eggs lol'''
[[dependencies.dracomelette]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dracomelette]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"